//! Execute a rendered statement against MySQL.

use crate::error::{Error, Result};
use crate::types::{Bind, NullOf};
use serde_json::Value;
use sqlx::mysql::MySql;

/// A bound list, as MySQL receives it: JSON text, read back by `JSON_TABLE`
/// (or, for the key-set operators, cast to JSON) in the statement. MySQL
/// has no array type, and this is what keeps `_in` one placeholder
/// whatever the list's length.
fn json_list<T: serde::Serialize>(items: &[Option<T>]) -> String {
    serde_json::to_string(items).expect("a list of scalars serialises")
}

/// Execute a single-statement SQL with bound parameters on any sqlx executor.
/// The SQL is expected to return exactly one row with one JSON column, as
/// [`crate::sql::render`] produces for [`Dialect::MySql`](crate::Dialect::MySql).
pub async fn execute_on<'c, E>(executor: E, sql: &str, binds: &[Bind]) -> Result<Value>
where
    E: sqlx::Executor<'c, Database = MySql>,
{
    use sqlx::Row;
    // The SQL is generated by our renderer (identifiers quoted, values always
    // bound), so asserting it safe here is sound.
    let row = bind_all(sqlx::query(sqlx::AssertSqlSafe(sql)), binds)
        .fetch_one(executor)
        .await
        .map_err(Error::Database)?;
    let json: sqlx::types::Json<Value> = row.try_get(0)?;
    Ok(json.0)
}

/// Run a [`MutationPlan`](crate::plan::MutationPlan). Not yet: the renderer
/// refuses a mutation for this dialect before a plan exists, so this is
/// unreachable until it does.
pub async fn execute_plan(
    _conn: &mut sqlx::MySqlConnection,
    _plan: &crate::plan::MutationPlan,
    _inputs: &crate::types::Inputs<'_>,
) -> Result<Value> {
    Err(Error::Unsupported {
        message: "mutations are not available on MySQL yet".into(),
    })
}

fn bind_all<'q>(
    mut q: sqlx::query::Query<'q, MySql, sqlx::mysql::MySqlArguments>,
    binds: &'q [Bind],
) -> sqlx::query::Query<'q, MySql, sqlx::mysql::MySqlArguments> {
    for b in binds {
        q = match b {
            Bind::Null(of) => match of {
                NullOf::Bool => q.bind(None::<bool>),
                NullOf::Int4 => q.bind(None::<i32>),
                NullOf::Int8 => q.bind(None::<i64>),
                NullOf::Float8 => q.bind(None::<f64>),
                NullOf::Text
                | NullOf::BoolArray
                | NullOf::Int4Array
                | NullOf::Int8Array
                | NullOf::Float8Array
                | NullOf::TextArray => q.bind(None::<String>),
            },
            Bind::Bool(v) => q.bind(*v),
            Bind::Int4(v) => q.bind(*v),
            Bind::Int8(v) => q.bind(*v),
            Bind::Float8(v) => q.bind(*v),
            Bind::Text(v) => q.bind(v.as_str()),
            Bind::BoolArray(v) => q.bind(json_list(v)),
            Bind::Int4Array(v) => q.bind(json_list(v)),
            Bind::Int8Array(v) => q.bind(json_list(v)),
            Bind::Float8Array(v) => q.bind(json_list(v)),
            Bind::TextArray(v) => q.bind(json_list(v)),
        };
    }
    q
}
