//! Execute a rendered statement against SQLite.

use crate::error::{Error, Result};
use crate::types::{Bind, NullOf};
use serde_json::Value;
use sqlx::sqlite::Sqlite;

/// A bound list, as SQLite receives it: JSON text, read back by `json_each`
/// in the statement. SQLite has no array type, and this is what keeps `_in`
/// one placeholder whatever the list's length.
fn json_list<T: serde::Serialize>(items: &[Option<T>]) -> String {
    serde_json::to_string(items).expect("a list of scalars serialises")
}

/// Execute a single-statement SQL with bound parameters on any sqlx executor.
/// The SQL is expected to return exactly one row with one column holding
/// JSON text, as [`crate::sql::render`] produces for [`Dialect::Sqlite`](crate::Dialect::Sqlite).
pub async fn execute_on<'c, E>(executor: E, sql: &str, binds: &[Bind]) -> Result<Value>
where
    E: sqlx::Executor<'c, Database = Sqlite>,
{
    // The SQL is generated by our renderer (identifiers quoted, values always
    // bound), so asserting it safe here is sound.
    let mut q = sqlx::query_scalar::<Sqlite, sqlx::types::Json<Value>>(sqlx::AssertSqlSafe(sql));
    for b in binds {
        q = match b {
            // SQLite types a value, not a parameter, so a null is a null; the
            // Rust type here only picks an `Encode` impl.
            Bind::Null(of) => match of {
                NullOf::Bool => q.bind(None::<bool>),
                NullOf::Int4 => q.bind(None::<i32>),
                NullOf::Int8 => q.bind(None::<i64>),
                NullOf::Float8 => q.bind(None::<f64>),
                NullOf::Text
                | NullOf::BoolArray
                | NullOf::Int4Array
                | NullOf::Int8Array
                | NullOf::Float8Array
                | NullOf::TextArray => q.bind(None::<String>),
            },
            Bind::Bool(v) => q.bind(*v),
            Bind::Int4(v) => q.bind(*v),
            Bind::Int8(v) => q.bind(*v),
            Bind::Float8(v) => q.bind(*v),
            Bind::Text(v) => q.bind(v.clone()),
            Bind::BoolArray(v) => q.bind(json_list(v)),
            Bind::Int4Array(v) => q.bind(json_list(v)),
            Bind::Int8Array(v) => q.bind(json_list(v)),
            Bind::Float8Array(v) => q.bind(json_list(v)),
            Bind::TextArray(v) => q.bind(json_list(v)),
        };
    }
    // `json('…')` on a non-JSON literal is the one way the rendered SQL can
    // raise, and it raises exactly when a column holds a value its declared
    // type does not admit (see `Dialect::value_as_json`). SQLite's message is
    // the same for every such case; this one says what it means here.
    let json = q.fetch_one(executor).await.map_err(|e| match &e {
        sqlx::Error::Database(db) if db.message().contains("malformed JSON") => Error::Decode(
            "SQLite reports malformed JSON: a column holds a value its declared type does not \
             admit — text in a BOOLEAN column, or a JSON column that is not JSON; the table is \
             not STRICT (see SchemaWarning::LooselyTypedTable)"
                .into(),
        ),
        _ => Error::Database(e),
    })?;
    Ok(json.0)
}
