//! TOML template rendering and helpers (URL redaction, header metadata).

/// Strip the password component of a postgres URL so it is safe to print.
///
/// Returns the original input unchanged when it cannot be parsed as a URL.
pub fn redact_url(raw: &str) -> String {
    let scheme_sep = match raw.find("://") {
        Some(i) => i + 3,
        None => return raw.to_string(),
    };
    let (scheme, rest) = raw.split_at(scheme_sep);
    let (authority, tail) = match rest.find('/') {
        Some(i) => (&rest[..i], &rest[i..]),
        None => (rest, ""),
    };
    let (userinfo, hostpart) = match authority.rfind('@') {
        Some(i) => (Some(&authority[..i]), &authority[i + 1..]),
        None => (None, authority),
    };
    match userinfo {
        Some(ui) => {
            let user = ui.split(':').next().unwrap_or("");
            if user.is_empty() {
                format!("{scheme}{hostpart}{tail}")
            } else {
                format!("{scheme}{user}@{hostpart}{tail}")
            }
        }
        None => raw.to_string(),
    }
}

/// Metadata embedded in the header of a generated schema.toml.
pub struct HeaderMeta {
    pub tool_version: String,
    pub timestamp_iso8601: String,
    pub redacted_source_url: String,
}

use crate::filter::TableFilter;
use vision_graphql::schema::introspect::{IntrospectedDb, IntrospectedTable};
use vision_graphql::schema::PgType;

const HEADER_PREFIX: &str = "# Generated by vision-gql";

/// Render a commented starter schema.toml from an introspected database.
///
/// Tables are emitted in alphabetical order. Every line outside of the input
/// content is `#`-prefixed, so the output is a no-op overlay until the user
/// uncomments specific stanzas.
pub fn toml_template(db: &IntrospectedDb, filter: &TableFilter, meta: &HeaderMeta) -> String {
    let mut out = String::new();
    write_header(&mut out, meta);

    let mut emitted_any = false;
    for ((schema, name), table) in &db.tables {
        if schema != "public" {
            continue;
        }
        if !filter.keep(name) {
            continue;
        }
        emitted_any = true;
        out.push('\n');
        write_table_stanza(&mut out, table, db);
    }
    if !emitted_any {
        out.push_str("\n# (no tables matched the filter)\n");
    }
    out
}

fn write_header(out: &mut String, meta: &HeaderMeta) {
    out.push_str(&format!(
        "# Generated by vision-gql {} on {}\n",
        meta.tool_version, meta.timestamp_iso8601
    ));
    out.push_str(&format!("# Source: {}\n", meta.redacted_source_url));
    out.push_str("# Uncomment any stanza below to override defaults from introspection.\n");
}

fn pg_type_short(t: &PgType) -> std::borrow::Cow<'static, str> {
    std::borrow::Cow::Borrowed(match t {
        PgType::Int4 => "int4",
        PgType::Int8 => "int8",
        PgType::Text => "text",
        PgType::Varchar => "varchar",
        PgType::Bool => "bool",
        PgType::Float4 => "float4",
        PgType::Float8 => "float8",
        PgType::Numeric => "numeric",
        PgType::Uuid => "uuid",
        PgType::Timestamp => "timestamp",
        PgType::TimestampTz => "timestamptz",
        PgType::Json => "json",
        PgType::Jsonb => "jsonb",
        PgType::Date => "date",
        PgType::Time => "time",
        PgType::Enum { schema, name } => {
            return std::borrow::Cow::Owned(format!("{schema}.{name}"));
        }
    })
}

fn write_table_stanza(out: &mut String, t: &IntrospectedTable, db: &IntrospectedDb) {
    out.push_str(&format!(
        "# ── {}.{} ─────────────────────────────\n",
        t.schema, t.name
    ));
    out.push_str("# columns: ");
    let mut first = true;
    for col in &t.columns {
        if !first {
            out.push_str(", ");
        }
        first = false;
        let pk = t.primary_key.iter().any(|p| p == &col.name);
        let nullable = if col.nullable { "?" } else { "" };
        let pk_marker = if pk { ", PK" } else { "" };
        out.push_str(&format!(
            "{} ({}{}{})",
            col.name,
            pg_type_short(&col.pg_type),
            nullable,
            pk_marker
        ));
    }
    out.push('\n');

    if t.foreign_keys.is_empty() {
        out.push_str("# foreign keys: (none)\n");
    } else {
        for fk in &t.foreign_keys {
            out.push_str(&format!(
                "# foreign keys: {}({}) -> {}({})\n",
                t.name,
                fk.from_columns.join(", "),
                fk.to_table,
                fk.to_columns.join(", "),
            ));
        }
    }
    out.push_str("#\n");
    out.push_str(&format!("# [tables.{}]\n", t.name));
    out.push_str(&format!("# expose_as = \"{}\"\n", t.name));
    out.push_str("# hide_columns = []\n");

    let derived = vision_graphql::schema::merge::derive_relations_from_fks(db);
    let mine: Vec<_> = derived
        .iter()
        .filter(|(src, _, _)| src == &t.name)
        .collect();
    for (_, rel_name, rel) in mine {
        let kind = match rel.kind {
            vision_graphql::schema::RelKind::Object => "object",
            vision_graphql::schema::RelKind::Array => "array",
        };
        out.push_str("#\n");
        out.push_str(&format!("# # {} relation derived from FK\n", kind));
        out.push_str(&format!("# [[tables.{}.relations]]\n", t.name));
        out.push_str(&format!("# name = \"{}\"\n", rel_name));
        out.push_str(&format!("# kind = \"{}\"\n", kind));
        out.push_str(&format!("# target = \"{}\"\n", rel.target_table));
        out.push_str("# mapping = [");
        let mut first = true;
        for (a, b) in &rel.mapping {
            if !first {
                out.push_str(", ");
            }
            first = false;
            out.push_str(&format!("[\"{}\", \"{}\"]", a, b));
        }
        out.push_str("]\n");
    }
}

#[cfg(test)]
mod render_tests {
    use super::*;
    use vision_graphql::schema::introspect::{IntrospectedColumn, IntrospectedForeignKey};

    fn meta() -> HeaderMeta {
        HeaderMeta {
            tool_version: "0.2.0".into(),
            timestamp_iso8601: "2026-05-09T00:00:00Z".into(),
            redacted_source_url: "postgres://u@h/db".into(),
        }
    }

    #[test]
    fn empty_db_renders_only_header_and_placeholder() {
        let db = IntrospectedDb::default();
        let f = TableFilter::new(None, None).unwrap();
        let out = toml_template(&db, &f, &meta());
        assert!(out.starts_with(HEADER_PREFIX));
        assert!(out.contains("(no tables matched"));
    }

    #[test]
    fn single_table_no_fk_renders_stanza() {
        let mut db = IntrospectedDb::default();
        db.tables.insert(
            ("public".into(), "users".into()),
            IntrospectedTable {
                schema: "public".into(),
                name: "users".into(),
                columns: vec![
                    IntrospectedColumn {
                        name: "id".into(),
                        pg_type: PgType::Int4,
                        nullable: false,
                    },
                    IntrospectedColumn {
                        name: "email".into(),
                        pg_type: PgType::Text,
                        nullable: true,
                    },
                ],
                primary_key: vec!["id".into()],
                unique_constraints: Default::default(),
                foreign_keys: vec![],
            },
        );
        let f = TableFilter::new(None, None).unwrap();
        let out = toml_template(&db, &f, &meta());
        assert!(out.contains("# ── public.users ─"));
        assert!(out.contains("id (int4, PK)"));
        assert!(out.contains("email (text?)"));
        assert!(out.contains("# foreign keys: (none)"));
        assert!(out.contains("# [tables.users]"));
    }

    #[test]
    fn fk_emits_relation_stanzas_on_both_sides() {
        let mut db = IntrospectedDb::default();
        db.tables.insert(
            ("public".into(), "users".into()),
            IntrospectedTable {
                schema: "public".into(),
                name: "users".into(),
                columns: vec![IntrospectedColumn {
                    name: "id".into(),
                    pg_type: PgType::Int4,
                    nullable: false,
                }],
                primary_key: vec!["id".into()],
                unique_constraints: Default::default(),
                foreign_keys: vec![],
            },
        );
        db.tables.insert(
            ("public".into(), "posts".into()),
            IntrospectedTable {
                schema: "public".into(),
                name: "posts".into(),
                columns: vec![
                    IntrospectedColumn {
                        name: "id".into(),
                        pg_type: PgType::Int4,
                        nullable: false,
                    },
                    IntrospectedColumn {
                        name: "user_id".into(),
                        pg_type: PgType::Int4,
                        nullable: false,
                    },
                ],
                primary_key: vec!["id".into()],
                unique_constraints: Default::default(),
                foreign_keys: vec![IntrospectedForeignKey {
                    constraint_name: "posts_user_id_fkey".into(),
                    from_columns: vec!["user_id".into()],
                    to_schema: "public".into(),
                    to_table: "users".into(),
                    to_columns: vec!["id".into()],
                }],
            },
        );
        let f = TableFilter::new(None, None).unwrap();
        let out = toml_template(&db, &f, &meta());
        // Object relation on `posts` side
        assert!(out.contains("# [[tables.posts.relations]]"));
        assert!(out.contains("# kind = \"object\""));
        assert!(out.contains("# target = \"users\""));
        // Array relation on `users` side
        assert!(out.contains("# [[tables.users.relations]]"));
        assert!(out.contains("# kind = \"array\""));
        assert!(out.contains("# target = \"posts\""));
        // FK summary line on posts
        assert!(out.contains("posts(user_id) -> users(id)"));
    }

    #[test]
    fn filter_excludes_non_matching_tables() {
        let mut db = IntrospectedDb::default();
        for n in ["users", "audit_log"] {
            db.tables.insert(
                ("public".into(), n.into()),
                IntrospectedTable {
                    schema: "public".into(),
                    name: n.into(),
                    columns: vec![IntrospectedColumn {
                        name: "id".into(),
                        pg_type: PgType::Int4,
                        nullable: false,
                    }],
                    primary_key: vec!["id".into()],
                    unique_constraints: Default::default(),
                    foreign_keys: vec![],
                },
            );
        }
        let ignore = vec!["audit_*".to_string()];
        let f = TableFilter::new(None, Some(&ignore)).unwrap();
        let out = toml_template(&db, &f, &meta());
        assert!(out.contains("# ── public.users ─"));
        assert!(!out.contains("audit_log"));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn redacts_password_keeps_user() {
        let s = redact_url("postgres://alice:supersecret@db.example.com:5432/myapp");
        assert_eq!(s, "postgres://alice@db.example.com:5432/myapp");
    }

    #[test]
    fn no_userinfo_passes_through() {
        let s = redact_url("postgres://db.example.com:5432/myapp");
        assert_eq!(s, "postgres://db.example.com:5432/myapp");
    }

    #[test]
    fn user_only_no_password() {
        let s = redact_url("postgres://alice@db.example.com/myapp");
        assert_eq!(s, "postgres://alice@db.example.com/myapp");
    }

    #[test]
    fn unparseable_returned_unchanged() {
        let s = redact_url("not-a-url");
        assert_eq!(s, "not-a-url");
    }

    #[test]
    fn no_path_redacts() {
        let s = redact_url("postgres://alice:pw@host:5432");
        assert_eq!(s, "postgres://alice@host:5432");
    }
}
