//! Execute generated SQL against PostgreSQL.

use crate::error::Result;
use crate::types::Bind;
use serde_json::Value;
use sqlx::postgres::Postgres;

/// Execute a single-statement SQL with bound parameters on any sqlx executor
/// (pool or open transaction connection). The SQL is expected to return
/// exactly one row with one column containing a JSON value (generated by
/// [`crate::sql::render`]).
pub async fn execute_on<'c, E>(executor: E, sql: &str, binds: &[Bind]) -> Result<Value>
where
    E: sqlx::Executor<'c, Database = Postgres>,
{
    // The SQL is generated by our renderer (identifiers quoted, values always
    // bound), so asserting it safe here is sound.
    let mut q = sqlx::query_scalar::<Postgres, Value>(sqlx::AssertSqlSafe(sql.to_string()));
    for b in binds {
        q = match b {
            Bind::Null => q.bind(None::<String>),
            Bind::Bool(v) => q.bind(*v),
            Bind::Int4(v) => q.bind(*v),
            Bind::Int8(v) => q.bind(*v),
            Bind::Float8(v) => q.bind(*v),
            Bind::Text(v) => q.bind(v.clone()),
        };
    }
    let json = q.fetch_one(executor).await?;
    Ok(json)
}

/// Execute against the pool. Preserves the pre-transaction-API call signature.
pub async fn execute(pool: &sqlx::PgPool, sql: &str, binds: &[Bind]) -> Result<Value> {
    execute_on(pool, sql, binds).await
}
