//! Execute generated SQL against PostgreSQL.

use crate::error::Result;
use crate::types::{Bind, NullOf};
use serde_json::Value;
use sqlx::postgres::Postgres;

/// Execute a single-statement SQL with bound parameters on any sqlx executor
/// (pool or open transaction connection). The SQL is expected to return
/// exactly one row with one column containing a JSON value (generated by
/// [`crate::sql::render`]).
pub async fn execute_on<'c, E>(executor: E, sql: &str, binds: &[Bind]) -> Result<Value>
where
    E: sqlx::Executor<'c, Database = Postgres>,
{
    // The SQL is generated by our renderer (identifiers quoted, values always
    // bound), so asserting it safe here is sound.
    // Borrowed, not copied: this runs on every request, and for a compiled
    // statement the SQL string is the one thing that never changes between them.
    let mut q = sqlx::query_scalar::<Postgres, Value>(sqlx::AssertSqlSafe(sql));
    for b in binds {
        q = match b {
            Bind::Null(of) => match of {
                NullOf::Bool => q.bind(None::<bool>),
                NullOf::Int4 => q.bind(None::<i32>),
                NullOf::Int8 => q.bind(None::<i64>),
                NullOf::Float8 => q.bind(None::<f64>),
                NullOf::Text => q.bind(None::<String>),
                NullOf::BoolArray => q.bind(None::<Vec<Option<bool>>>),
                NullOf::Int4Array => q.bind(None::<Vec<Option<i32>>>),
                NullOf::Int8Array => q.bind(None::<Vec<Option<i64>>>),
                NullOf::Float8Array => q.bind(None::<Vec<Option<f64>>>),
                NullOf::TextArray => q.bind(None::<Vec<Option<String>>>),
            },
            Bind::Bool(v) => q.bind(*v),
            Bind::Int4(v) => q.bind(*v),
            Bind::Int8(v) => q.bind(*v),
            Bind::Float8(v) => q.bind(*v),
            Bind::Text(v) => q.bind(v.clone()),
            Bind::BoolArray(v) => q.bind(v.clone()),
            Bind::Int4Array(v) => q.bind(v.clone()),
            Bind::Int8Array(v) => q.bind(v.clone()),
            Bind::Float8Array(v) => q.bind(v.clone()),
            Bind::TextArray(v) => q.bind(v.clone()),
        };
    }
    let json = q.fetch_one(executor).await?;
    Ok(json)
}

/// Execute against the pool. [`execute_on`] takes a pool as it takes any
/// executor; nothing in the crate calls this any more.
#[deprecated(
    since = "0.22.0",
    note = "use `execute_on`, which takes a pool as it takes any executor"
)]
pub async fn execute(pool: &sqlx::PgPool, sql: &str, binds: &[Bind]) -> Result<Value> {
    execute_on(pool, sql, binds).await
}
